[package]
name = "gltfpack-sys"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gltfpack-rs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
cmake = "0.1"
cc = "1.0"
